sunsurfers/urls.py
from django.conf import settings
from django.urls import path, include
from django.contrib.gis import admin
from django.shortcuts import render

from surfers.api import v1_api
import randomcoffee.views

from . import auth


def login_view(request):
    # XXX: "next" passthrough doesn't work when using JS-backed redirects and
    # auth widgets (they are unfortunately laying out of the PSA login flow)
    if "next" in request.GET:
        request.session["next"] = request.GET["next"]
    return render(request, "login.html", {"tgauth_bot": settings.TGAUTH_BOT})


urlpatterns = [
    path("", include("surfers.urls")),
    path("admin/", admin.site.urls),
    path("api/", include(v1_api.urls)),
    path("checklist/", include("checklist.urls")),
    path("login/", login_view),
    path(
        "register-by-token/<backend>/",
        auth.register_by_access_token,
        "register_by_access_token",
    ),
    path("social-auth/", include("social_django.urls", namespace="social")),
    path("tg/", include("tgauth.urls")),
    path("randomcoffee/", include("randomcoffee.urls")),
]

if settings.DEBUG:
    from django.conf.urls.static import static

    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT
    )
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

surfers/urls.py
from django.urls import path
from django.views.generic import TemplateView

from surfers import views


app_name = "surfers"
urlpatterns = [
    path("map", views.sunmap, name="sunmap"),
    path(
        "policy",
        TemplateView.as_view(template_name="policy.html"),
        name="policy",
    ),
    path("latest", views.latest, name="latest_geojson"),
]

tgauth/urls.py
from django.urls import path

from tgauth import views


app_name = "tgauth"
urlpatterns = [
    path("webhook/<token>", views.botapi_view, name="webhook"),
    path("login/<token>", views.login_view, name="login"),
]

surfers/models.py
from django.contrib.gis.db import models
from django.conf import settings


class LatestPoint(models.Model):
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE
    )
    updated_at = models.DateTimeField(auto_now=True)
    point = models.PointField(geography=True)

    class Meta:
        ordering = ["-updated_at"]
        verbose_name_plural = "Latest Point"


class Contact(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE
    )
    contact_type = models.CharField(
        max_length=32,
        choices=[
            # XXX: или показывать по-дефолту из auth.User?
            # против - пользователь должен явно указать публичный e-mail,
            # auth.User.email - не публичный
            ("EMAIL", "Email"),
            # XXX: нужен тут дефолтный или пусть в UserLocation?
            # ('PHONE', 'Phone'),
            ("FB", "Facebook"),
            ("VK", "ВКонтакте"),
            ("IG", "Instagram"),
            ("TW", "Twitter"),
            # XXX: всё это обычно один номер телефона, но наверно лучше дать явно
            # указать
            ("TELEGRAM", "Telegram"),
            ("WHATSUP", "WhatsUp"),
            ("VIBER", "Viber"),
            ("OTHER", "Other"),
        ],
    )
    value = models.CharField(max_length=255)
    description = models.CharField(max_length=1024)


class Achievment(models.Model):
    name = models.CharField(max_length=255)
    base_score = models.IntegerField()


class UserAchievment(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE
    )
    achievment = models.ForeignKey(Achievment, on_delete=models.CASCADE)
    score = models.IntegerField()
    created_at = models.DateTimeField(auto_now_add=True)


class Endorsement(models.Model):
    achievment = models.ForeignKey(UserAchievment, on_delete=models.CASCADE)
    endorsed_by = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE
    )


class Location(models.Model):
    name = models.CharField(max_length=255)
    geo = models.GeometryField()


class UserLocation(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE
    )
    location = models.ForeignKey(Location, on_delete=models.CASCADE)
    date_from = models.DateTimeField()
    date_till = models.DateTimeField()
    contact_phone = models.CharField(max_length=32)


class Track(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE
    )
    point = models.PointField()
    timestamp = models.DateTimeField(auto_now_add=True)

surfers/views.py
from datetime import timedelta

import geojson

from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.http import HttpResponse
from django.shortcuts import render
from django.utils import timezone

from surfers import api
from surfers.models import LatestPoint


@login_required
def sunmap(request):
    return render(
        request, "sunmap.html", {"mapbox_token": settings.MAPBOX_TOKEN}
    )


@login_required
def latest(request):
    points = LatestPoint.objects.filter(
        updated_at__gt=timezone.now() - timedelta(days=14)
    ).order_by("-updated_at")[:100]
    collection = geojson.FeatureCollection(
        [
            geojson.Feature(
                geometry=geojson.Point(i.point.coords),
                properties={
                    "user": i.user.get_full_name(),
                    "user_url": api.user.get_resource_uri(i.user),
                    "updated_at": i.updated_at.isoformat(),
                },
            )
            for i in points
        ]
    )
    return HttpResponse(
        geojson.dumps(collection), content_type="application/json"
    )

surfers/templates/login.html
<!doctype html>
<html>
  <head>
<style>
html, body, .centered { height: 100%; margin: 0; }
.centered {
    display: flex;
    flex-flow: column;
	align-items: center;
    justify-content: center;
}
.facebook-button {
	display: flex;
	align-items: center;
    background-color: #4267b2;
    border-radius: 4px;
    color: white;
    font-family: Helvetica, Arial, sans-serif;
    font-size: 16px;
    letter-spacing: 0.25px;
    text-decoration: none;
    padding: 8px;
    margin-top: 8px;
}
.facebook-button svg {
    display: inline;
}
.facebook-button span {
    padding-top: 4px;
    padding-left: 25px;
    padding-right: 25px;
}
</style>
  </head>
  <body>
      <div class="centered">
          <script async src="https://telegram.org/js/telegram-widget.js?4"
              data-telegram-login="{{ tgauth_bot }}" data-size="large"
              data-auth-url="https://{{ request.get_host }}{% url "social:complete" "telegram" %}"
              data-request-access="write"></script>
          <a class="facebook-button" href="{% url "social:begin" "facebook" %}">
              <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 216 216" width="24px" height="24px"><path fill="#FFFFFF" d="M204.1 0H11.9C5.3 0 0 5.3 0 11.9v192.2c0 6.6 5.3 11.9 11.9 11.9h103.5v-83.6H87.2V99.8h28.1v-24c0-27.9 17-43.1 41.9-43.1 11.9 0 22.2.9 25.2 1.3v29.2h-17.3c-13.5 0-16.2 6.4-16.2 15.9v20.8h32.3l-4.2 32.6h-28V216h55c6.6 0 11.9-5.3 11.9-11.9V11.9C216 5.3 210.7 0 204.1 0z"></path></svg>
              <span>Вход через Facebook</span>
          </a>
      </div>
  </body>
</html>

surfers/templates/policy.html
<html>
    <head>

<style>
body {
}
h1 {
}
h2 {
}
p {
}
</style>

    </head>
    <body>

<h1>Политика в отношении обработки персональных данных</h1>

<h2>1. Общие положения</h2>

<p>Настоящая политика обработки персональных данных составлена в соответствии с
требованиями Федерального закона от 27.07.2006. №152-ФЗ «О персональных данных»
и определяет порядок обработки персональных данных и меры по обеспечению
безопасности персональных данных GoodDeed.Me (далее –
Оператор).</p>

<p>Оператор ставит своей важнейшей целью и условием осуществления своей
деятельности соблюдение прав и свобод человека и гражданина при обработке
его персональных данных, в том числе защиты прав на неприкосновенность
частной жизни, личную и семейную тайну.</p>

<p>Настоящая политика Оператора в отношении обработки персональных данных
(далее – Политика) применяется ко всей информации, которую Оператор может
получить о посетителях веб-сайта <a href="https://gooddeed.me">https://gooddeed.me</a>.</p>


<h2>2. Основные понятия, используемые в Политике</h2>

<ol>
<li>Автоматизированная обработка персональных данных – обработка персональных данных с помощью средств вычислительной техники;</li>
<li>Блокирование персональных данных – временное прекращение обработки персональных данных (за исключением случаев, если обработка необходима для уточнения персональных данных);</li>
<li>Веб-сайт – совокупность графических и информационных материалов, а также программ для ЭВМ и баз данных, обеспечивающих их доступность в сети интернет по сетевому адресу <a href="https://gooddeed.me">https://gooddeed.me</a>;</li>
<li>Информационная система персональных данных — совокупность содержащихся в базах данных персональных данных, и обеспечивающих их обработку информационных технологий и технических средств;</li>
<li>Обезличивание персональных данных — действия, в результате которых невозможно определить без использования дополнительной информации принадлежность персональных данных конкретному Пользователю или иному субъекту персональных данных;</li>
<li>Обработка персональных данных – любое действие (операция) или совокупность действий (операций), совершаемых с использованием средств автоматизации или без использования таких средств с персональными данными, включая сбор, запись, систематизацию, накопление, хранение, уточнение (обновление, изменение), извлечение, использование, передачу (распространение, предоставление, доступ), обезличивание, блокирование, удаление, уничтожение персональных данных;</li>
<li>Оператор – государственный орган, муниципальный орган, юридическое или физическое лицо, самостоятельно или совместно с другими лицами организующие и (или) осуществляющие обработку персональных данных, а также определяющие цели обработки персональных данных, состав персональных данных, подлежащих обработке, действия (операции), совершаемые с персональными данными;</li>
<li>Персональные данные – любая информация, относящаяся прямо или косвенно к определенному или определяемому Пользователю веб-сайта <a href="https://gooddeed.me">https://gooddeed.me</a>;</li>
<li>Пользователь – любой посетитель веб-сайта <a href="https://gooddeed.me">https://gooddeed.me</a>;</li>
<li>Предоставление персональных данных – действия, направленные на раскрытие персональных данных определенному лицу или определенному кругу лиц;</li>
<li>Распространение персональных данных – любые действия, направленные на раскрытие персональных данных неопределенному кругу лиц (передача персональных данных) или на ознакомление с персональными данными неограниченного круга лиц, в том числе обнародование персональных данных в средствах массовой информации, размещение в информационно-телекоммуникационных сетях или предоставление доступа к персональным данным каким-либо иным способом;</li>
<li>Трансграничная передача персональных данных – передача персональных данных на территорию иностранного государства органу власти иностранного государства, иностранному физическому или иностранному юридическому лицу;</li>
<li>Уничтожение персональных данных – любые действия, в результате которых персональные данные уничтожаются безвозвратно с невозможностью дальнейшего восстановления содержания персональных данных в информационной системе персональных данных и (или) результате которых уничтожаются материальные носители персональных данных.</li>
</ol>


<h2>3. Оператор может обрабатывать следующие персональные данные Пользователя</h2>

<ol>
<li>Фамилия, имя, отчество;</li>
<li>Фотографии;</li>
<li>Географические координаты;</li>
<li>Также на сайте происходит сбор и обработка обезличенных данных о посетителях (в т.ч. файлов «cookie») с помощью сервисов интернет-статистики (Яндекс Метрика и Гугл Аналитика и других).</li>
<li>Вышеперечисленные данные далее по тексту Политики объединены общим понятием Персональные данные.</li>
</ol>


<h2>4. Цели обработки персональных данных</h2>

<ol>
<li>Цель обработки персональных данных Пользователя — предоставление доступа Пользователю к сервисам, информации и/или материалам, содержащимся на веб-сайте.</li>
<li>Также Оператор имеет право направлять Пользователю уведомления о новых продуктах и услугах, специальных предложениях и различных событиях. Пользователь всегда может отказаться от получения информационных сообщений, направив Оператору письмо на адрес электронной почты <a href="mailto:policy@gooddeed.me">policy@gooddeed.me</a> с пометкой «Отказ от уведомлениях о новых продуктах и услугах и специальных предложениях».</li>
<li>Обезличенные данные Пользователей, собираемые с помощью сервисов интернет-статистики, служат для сбора информации о действиях Пользователей на сайте, улучшения качества сайта и его содержания.</li>
</ol>


<h2>5. Правовые основания обработки персональных данных</h2>

<ol>
<li>Оператор обрабатывает персональные данные Пользователя только в случае их заполнения и/или отправки Пользователем самостоятельно через специальные формы, расположенные на сайте <a href="https://gooddeed.me">https://gooddeed.me</a>. Заполняя соответствующие формы и/или отправляя свои персональные данные Оператору, Пользователь выражает свое согласие с данной Политикой.</li>
<li>Оператор обрабатывает обезличенные данные о Пользователе в случае, если это разрешено в настройках браузера Пользователя (включено сохранение файлов «cookie» и использование технологии JavaScript).</li>
</ol>


<h2>6. Порядок сбора, хранения, передачи и других видов обработки персональных данных</h2>

<p>Безопасность персональных данных, которые обрабатываются Оператором, обеспечивается путем реализации правовых, организационных и технических мер, необходимых для выполнения в полном объеме требований действующего законодательства в области защиты персональных данных.</p>

<ol>
<li>Оператор обеспечивает сохранность персональных данных и принимает все возможные меры, исключающие доступ к персональным данным неуполномоченных лиц.</li>
<li>Персональные данные Пользователя никогда, ни при каких условиях не будут переданы третьим лицам, за исключением случаев, связанных с исполнением действующего законодательства.</li>
<li>В случае выявления неточностей в персональных данных, Пользователь может актуализировать их самостоятельно, путем направления Оператору уведомление на адрес электронной почты Оператора <a href="mailto:policy@gooddeed.me">policy@gooddeed.me</a> с пометкой «Актуализация персональных данных».</li>
<li>Срок обработки персональных данных является неограниченным. Пользователь может в любой момент отозвать свое согласие на обработку персональных данных, направив Оператору уведомление посредством электронной почты на электронный адрес Оператора <a href="mailto:policy@gooddeed.me">policy@gooddeed.me</a> с пометкой «Отзыв согласия на обработку персональных данных».</li>
</ol>

<h2>7. Трансграничная передача персональных данных</h2>

<ol>
<li>Оператор до начала осуществления трансграничной передачи персональных данных обязан убедиться в том, что иностранным государством, на территорию которого предполагается осуществлять передачу персональных данных, обеспечивается надежная защита прав субъектов персональных данных.</li>
<li>Трансграничная передача персональных данных на территории иностранных государств, не отвечающих вышеуказанным требованиям, может осуществляться только в случае наличия согласия в письменной форме субъекта персональных данных на трансграничную передачу его персональных данных и/или исполнения договора, стороной которого является субъект персональных данных.</li>
</ol>


<h2>8. Заключительные положения</h2>

<ol>
<li>Пользователь может получить любые разъяснения по интересующим вопросам, касающимся обработки его персональных данных, обратившись к Оператору с помощью электронной почты <a href="mailto:policy@gooddeed.me">policy@gooddeed.me</a>.</li>
<li>В данном документе будут отражены любые изменения политики обработки персональных данных Оператором. Политика действует бессрочно до замены ее новой версией.</li>
<li>Актуальная версия Политики в свободном доступе расположена в сети Интернет по адресу <a href="https://gooddeed.me">https://gooddeed.me</a>/policy/.</li>
</ol>

    </body>
</html>

surfers/templates/sunmap.html
{% load static %}
<html>

<head>
    <meta charset='utf-8' />
    <title>#SUNMAP</title>
    <meta name='viewport' content='initial-scale=1,maximum-scale=1,user-scalable=no' />
    <script src='https://api.mapbox.com/mapbox-gl-js/v0.47.0/mapbox-gl.js'></script>
    <link href='https://api.mapbox.com/mapbox-gl-js/v0.47.0/mapbox-gl.css' rel='stylesheet' />
    <style>
        body { margin:0; padding:0; }
        #map { position:absolute; top:0; bottom:0; width:100%; }
    </style>
</head>

<body>
    <div id='map'></div>
    <script>

mapboxgl.accessToken = "{{ mapbox_token }}";

var map = new mapboxgl.Map({
    container: "map",
    //style: "mapbox://styles/mapbox/streets-v10"
    style: "{% static "basic-v9.json" %}"
});

map.on("load", function() {

    map.addSource("points", {
        type: 'geojson',
        data: "{% url "surfers:latest_geojson" %}",
        cluster: true
    });

    map.addLayer({
        "id": "unclustered-points",
        "type": "symbol",
        "source": "points",
        "layout": {
            "icon-image": "marker-15",
            "icon-anchor": "bottom",
            "text-field": "{user}",
            "text-anchor": "bottom",
            "text-offset": [0, -1.2],
        }
    });


    var layers = [
        [150, '#f28cb1'],
        [20, '#f1f075'],
        [0, '#51bbd6']
    ];

    layers.forEach(function (layer, i) {
        map.addLayer({
            "id": "cluster-" + i,
            "type": "circle",
            "source": "points",
            "paint": {
                "circle-color": layer[1],
                "circle-radius": 18
            },
            "filter": i === 0 ?
                [">=", "point_count", layer[0]] :
                ["all",
                    [">=", "point_count", layer[0]],
                    ["<", "point_count", layers[i - 1][0]]]
        });
    });

    // Add a layer for the clusters' count labels
    map.addLayer({
        "id": "cluster-count",
        "type": "symbol",
        "source": "points",
        "layout": {
            "text-field": "{point_count}",
            "text-font": [
                "DIN Offc Pro Medium",
                "Arial Unicode MS Bold"
            ],
            "text-size": 12
        }
    });

});
    </script>
</body>

</html>