checklist/urls.py
from django.urls import path

from checklist import views

app_name = "checklist"
urlpatterns = [
    path("", views.checklists, name="checklists"),
    path("<slug>", views.checklist, name="checklist"),
]

sunsurfers/urls.py
from django.conf import settings
from django.urls import path, include
from django.contrib.gis import admin
from django.shortcuts import render

from surfers.api import v1_api
import randomcoffee.views

from . import auth


def login_view(request):
    # XXX: "next" passthrough doesn't work when using JS-backed redirects and
    # auth widgets (they are unfortunately laying out of the PSA login flow)
    if "next" in request.GET:
        request.session["next"] = request.GET["next"]
    return render(request, "login.html", {"tgauth_bot": settings.TGAUTH_BOT})


urlpatterns = [
    path("", include("surfers.urls")),
    path("admin/", admin.site.urls),
    path("api/", include(v1_api.urls)),
    path("checklist/", include("checklist.urls")),
    path("login/", login_view),
    path(
        "register-by-token/<backend>/",
        auth.register_by_access_token,
        "register_by_access_token",
    ),
    path("social-auth/", include("social_django.urls", namespace="social")),
    path("tg/", include("tgauth.urls")),
    path("randomcoffee/", include("randomcoffee.urls")),
]

if settings.DEBUG:
    from django.conf.urls.static import static

    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT
    )
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

tgauth/urls.py
from django.urls import path

from tgauth import views


app_name = "tgauth"
urlpatterns = [
    path("webhook/<token>", views.botapi_view, name="webhook"),
    path("login/<token>", views.login_view, name="login"),
]

checklist/models.py
from django.db import models
from django.conf import settings


class TelegramBot(models.Model):
    username = models.CharField(max_length=64)
    token = models.CharField(max_length=80)
    webhook_url = models.CharField(max_length=64, unique=True)


class Checklist(models.Model):
    name = models.CharField(max_length=128)
    slug = models.CharField(max_length=32, unique=True)
    logo_image = models.ImageField(null=True, blank=True)
    is_active = models.BooleanField()
    bot = models.ForeignKey(
        TelegramBot, models.SET_NULL, null=True, blank=True
    )

    def __str__(self):
        return self.name


class Item(models.Model):
    checklist = models.ForeignKey(Checklist, models.CASCADE)
    ordernum = models.IntegerField(default=0)
    text = models.CharField(max_length=512)
    answer_type = models.CharField(
        max_length=4,
        choices=[("bool", "Yes/No"), ("text", "Text")],
        default="bool",
    )

    def __str__(self):
        return self.text


# a set of answers of a User to items in a checklist
class Session(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, models.CASCADE)
    checklist = models.ForeignKey(Checklist, models.CASCADE)


class YesNoAnswer(models.Model):
    session = models.ForeignKey(Session, models.CASCADE)
    item = models.ForeignKey(Item, models.CASCADE)
    value = models.BooleanField()


class TextAnswer(models.Model):
    session = models.ForeignKey(Session, models.CASCADE)
    item = models.ForeignKey(Item, models.CASCADE)
    value = models.CharField(max_length=1024)

checklist/views.py
from datetime import date
import logging

from cairosvg import svg2png
import svgwrite

from django.shortcuts import render
from django.http import (
    HttpResponse,
    HttpResponseNotFound,
    HttpResponseNotAllowed,
)
from checklist.models import Checklist


def checklists(request):
    return render(
        request,
        "checklists.html",
        {"object_list": Checklist.objects.filter(is_active=True)},
    )


def checklist(request, slug):
    try:
        checklist = Checklist.objects.get(slug=slug)
        items = list(checklist.item_set.order_by("ordernum"))
    except Checklist.DoesNotExist:
        return HttpResponseNotFound("<h1>Page not found</h1>")
    today = date.today()
    if request.method == "GET":
        return render(
            request,
            "checklist.html",
            {
                "checklist": checklist,
                "items": items,
                "today": today.strftime("%a %b %d %Y"),
                "today_iso": today.isoformat(),
            },
        )
    elif request.method == "POST":

        width = 440
        line_height = 25
        padding_top = 100
        height = padding_top + line_height * (len(items) + 1)

        dwg = svgwrite.Drawing()
        dwg["width"] = width
        dwg["height"] = height
        path = (
            "M16.667,62.167c3.109,5.55,7.217,10.591,10.926,15.75 "
            "c2.614,3.636,5.149,7.519,8.161,10.853c-0.046-0.051,"
            "1.959,2.414,2.692,2.343c0.895-0.088,6.958-8.511,6.014-7.3 "
            "c5.997-7.695,11.68-15.463,16.931-23.696c6.393-10.025,"
            "12.235-20.373,18.104-30.707C82.004,24.988,84.802,20.601,87,16"
        )
        dwg.defs.add(
            dwg.path(
                path,
                fill="none",
                stroke="blue",
                stroke_width=".7em",
                id="checkmark",
            )
        )
        r = dwg.add(dwg.rect((0, 0), rx=6, ry=6))
        r["width"] = width
        r["height"] = height
        r["fill"] = "white"
        g = dwg.add(
            dwg.g(font_family="Amatic SC", font_weight="bold", font_size=24)
        )
        if checklist.logo_image:
            img = g.add(dwg.image(checklist.logo_image.path))
            img["x"] = 20
            img["y"] = 20
            img["width"] = 60
            img["height"] = 60
        g.add(
            dwg.text(
                "My checklist for %s:" % today.strftime("%a %b %d %Y"),
                (120, 60),
            )
        )
        for n, i in enumerate(items):
            y = padding_top + n * line_height
            item_g = g.add(dwg.g(transform="translate(10,%d)" % y))
            r = item_g.add(
                dwg.rect(fill="none", stroke_width=".1em", stroke="black")
            )
            r["x"] = line_height * 0.5
            r["y"] = int(line_height * 0.35)
            r["width"] = int(line_height * 0.6)
            r["height"] = int(line_height * 0.6)
            if request.POST.get(str(i.id)) == "on":
                item_g.add(
                    dwg.use(
                        "#checkmark", transform="translate(7, -8) scale(0.3)"
                    )
                )
            item_g.add(dwg.text(i.text, (45, line_height)))
        svg = dwg.tostring()

        logging.debug("Generated SVG: %s", svg)
        png = svg2png(bytestring=svg)
        response = HttpResponse(png, content_type="image/png")
        response["Content-Disposition"] = (
            'attachment; filename="%s-%s.png"'
            % (checklist.slug, today.isoformat())
        )
        return response
    else:
        return HttpResponseNotAllowed("<h1>Response not allowed</h1>")

checklist/templates/checklist.html
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>[Checklist] {{ checklist.name }}</title>
  </head>
  <body>
    <div>
      <div style="text-align: center">
        {% if checklist.logo_image %}
        <img src="{{ checklist.logo_image.url }}" alt="" width="72" height="72">
        {% endif %}
        <h2>{{ checklist.name }}</h2>
      </div>
      <div style="max-width: 420px; margin: auto;">
        <form method='POST'>
          {% csrf_token %}
          <input id="today" type="hidden" name="date" value="{{ today_iso }}" />
          <script>document.getElementById("today").value = (new Date()).toISOString().substring(0, 10)</script>
          <div id="answers">
            <p>My checklist for {{today}}:</p>
            {% for item in items %}
            {% if item.answer_type == 'bool' %}
            <div>
              <input type="checkbox" name="{{ item.pk }}" id="{{ item.pk }}" />
              <label for="{{ item.pk }}">{{ item.text }}</label>
            </div>
            {% else %}
            <div>
              <label for="{{ item.pk }}">{{ item.text }}</label>
              <br/>
              <textarea name="{{ item.pk }}" id="{{ item.pk }}"></textarea>
            </div>
            {% endif %}
            {% endfor %}
          </div>
          <p>
            <button type="submit" id="done">Done!</button>
          </p>
        </form>
      </div>
    </div>
  </body>
</html>

checklist/templates/checklists.html
<!doctype html>
<html>
  <head></head>
  <body>
      <ul>
      {% for i in object_list %}
      <a href="{% url 'checklist:checklist' i.slug %}">{{ i.name }}</a>
      {% endfor %}
      </ul>
  </body>
</html>